-- iCarz database schema (utf8mb4) — import via phpMyAdmin or run admin/setup.php
CREATE DATABASE IF NOT EXISTS icarz CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE icarz;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(60) NOT NULL UNIQUE,
  pass VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sellers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  area VARCHAR(120) NOT NULL DEFAULT '',
  dist VARCHAR(60) NOT NULL DEFAULT '',
  eta VARCHAR(60) NOT NULL DEFAULT '',
  rating VARCHAR(12) NOT NULL DEFAULT '',
  jobs VARCHAR(60) NOT NULL DEFAULT '',
  fee INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  brand VARCHAR(60) NOT NULL DEFAULT '',
  name VARCHAR(160) NOT NULL,
  cat VARCHAR(20) NOT NULL DEFAULT 'car',
  for_car VARCHAR(160) NOT NULL DEFAULT '',
  price INT NOT NULL DEFAULT 0,
  old INT NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 10,
  pct INT NOT NULL DEFAULT 0,
  rating VARCHAR(12) NOT NULL DEFAULT '',
  sold VARCHAR(20) NOT NULL DEFAULT '',
  warranty VARCHAR(120) NOT NULL DEFAULT '',
  seller_id INT NOT NULL DEFAULT 1,
  hot VARCHAR(12) NOT NULL DEFAULT '',
  grad VARCHAR(160) NOT NULL DEFAULT '',
  label VARCHAR(160) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(30) NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'buy',
  title VARCHAR(220) NOT NULL,
  addr VARCHAR(220) NOT NULL DEFAULT '',
  time VARCHAR(80) NOT NULL DEFAULT '',
  total INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (status), INDEX (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
